"""add email and confirm

Revision ID: 083506dde27f
Revises: b0521d04f009
Create Date: 2026-07-31 22:50:40.998872

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '083506dde27f'
down_revision = 'b0521d04f009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)  # type: ignore
    existing_tables = inspector.get_table_names()
    if "_alembic_tmp_message" in existing_tables:
        op.drop_table("_alembic_tmp_message")
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('verified', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('verified')
        batch_op.drop_column('email')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=200), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), server_default=sa.text("'noemail@example.com'"), nullable=False),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
