"""add description and show_email for user profile

Revision ID: 383c1fac9a0d
Revises: 86e2b5fe8bca
Create Date: 2026-08-07 14:39:28.649049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383c1fac9a0d'
down_revision = '86e2b5fe8bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('show_email', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('show_email')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
