"""fix verified

Revision ID: 3e2271f3c6fc
Revises: 083506dde27f
Create Date: 2026-08-02 11:13:36.452734

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '3e2271f3c6fc'
down_revision = '083506dde27f'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = inspect(conn)  # type: ignore
    existing_tables = inspector.get_table_names()
    if "_alembic_tmp_message" in existing_tables:
        op.drop_table("_alembic_tmp_message")
    if "_alembic_tmp_user" in existing_tables:
        op.drop_table("_alembic_tmp_user")
    op.execute("UPDATE user SET created_at = '2026-08-01' WHERE created_at IS NULL;")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
